"""Reporting additions: by-rule grouping, root-cause hints, SARIF, HTML."""

from tods_validate.findings import Finding, Severity
from tods_validate.report import (
    REPORT_SCHEMA_VERSION,
    by_rule,
    render_html,
    render_markdown,
    render_sarif,
    render_text,
)


def _findings(rule_id: str, n: int, severity: Severity = Severity.ERROR) -> list[Finding]:
    return [
        Finding(rule_id=rule_id, severity=severity, file="run_events.txt", row=i, message=f"m{i}")
        for i in range(2, 2 + n)
    ]


def test_by_rule_counts() -> None:
    findings = _findings("TODS-E307", 3) + _findings("TODS-E308", 1)
    counts = by_rule(findings)
    assert counts["TODS-E307"] == 3
    assert counts["TODS-E308"] == 1


def test_text_shows_breakdown_and_path_to_green() -> None:
    text = render_text(_findings("TODS-E307", 2), "feed/")
    assert "By rule: TODS-E307 ×2" in text
    assert "away from a clean run" in text


def test_text_shows_root_cause_hint_when_clustered() -> None:
    text = render_text(_findings("TODS-E307", 6), "feed/")
    assert "hint:" in text
    assert "stale" in text


def test_text_hint_includes_worked_example_when_clustered() -> None:
    text = render_text(_findings("TODS-E307", 6), "feed/")
    assert "Before:" in text
    assert "After:" in text


def test_markdown_hint_includes_worked_example_when_clustered() -> None:
    markdown = render_markdown(_findings("TODS-E307", 6), "feed/")
    assert "hint:" in markdown
    assert "Before:" in markdown
    assert "After:" in markdown


def test_max_findings_hides_overflow() -> None:
    text = render_text(_findings("TODS-E307", 10), "feed/", max_findings=3)
    assert "7 more finding(s) not shown" in text


def test_sarif_lists_rules_and_results() -> None:
    import json

    sarif = json.loads(render_sarif(_findings("TODS-E307", 2), "feed/"))
    driver = sarif["runs"][0]["tool"]["driver"]
    assert {r["id"] for r in driver["rules"]} == {"TODS-E307"}
    assert len(sarif["runs"][0]["results"]) == 2
    loc = sarif["runs"][0]["results"][0]["locations"][0]["physicalLocation"]
    assert loc["artifactLocation"]["uri"] == "run_events.txt"


def test_sarif_help_uri_is_a_stable_rule_page() -> None:
    """helpUri points at the permanent per-rule page (EXP-08), not the spec

    citation directly, so links keep resolving even if the spec text moves.
    The spec citation itself is not lost -- it survives as a property.
    """
    import json

    from tods_validate.report import RULE_PAGE_BASE
    from tods_validate.rules import all_rules

    sarif = json.loads(render_sarif(_findings("TODS-E307", 1), "feed/"))
    descriptor = sarif["runs"][0]["tool"]["driver"]["rules"][0]
    rule = next(r for r in all_rules() if r.id == "TODS-E307")
    assert descriptor["helpUri"] == f"{RULE_PAGE_BASE}{rule.id}.html"
    assert descriptor["helpUri"].endswith(f"{rule.id}.html")
    assert descriptor["properties"]["specSection"] == rule.spec_section


def test_html_escapes_and_is_standalone() -> None:
    nasty = [Finding(rule_id="TODS-E999", severity=Severity.ERROR, message="<script>x</script>")]
    out = render_html(nasty, "feed/")
    assert "<script>x</script>" not in out  # escaped
    assert "&lt;script&gt;" in out


def test_html_report_is_accessible() -> None:
    out = render_html(_findings("TODS-E307", 2), "feed/")
    # Declared language and a responsive viewport so the page reflows on zoom.
    assert "<html lang='en'>" in out
    assert "name='viewport'" in out
    # Document landmarks give assistive tech an outline.
    assert "<header>" in out
    assert "<main>" in out
    # The findings table is navigable: a caption plus column-scoped headers.
    assert "<caption>" in out
    assert out.count("scope='col'") == 4
    # Severity reaches a screen reader as a word, not color alone.
    assert ">ERROR<" in out


def test_html_severity_colors_clear_contrast() -> None:
    # The info green was lightened away from the original low-contrast #0b5 so
    # all three severities clear WCAG AA (4.5:1) on the white background.
    out = render_html([], "feed/")
    assert "#0b5" not in out
    assert ".sev-info{color:#0a7d3f}" in out


def test_markdown_stamp_is_optional() -> None:
    plain = render_markdown(_findings("TODS-E307", 1), "feed/")
    stamped = render_markdown(_findings("TODS-E307", 1), "feed/", stamp=True)
    assert "Generated by tods-validate" not in plain
    assert "Generated by tods-validate" in stamped


def test_report_schema_version_is_set() -> None:
    assert REPORT_SCHEMA_VERSION
